version: '3.5'

networks:
  localdev:
    name: localdev

services:
  main-api:
    build: UsersApi
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - db-server
    networks:
      - localdev

  db-server:
    image: mongo
    container_name: db-server
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
